server:
  port: 8088

spring:
  jpa:
    properties:
      hibernate:
        show-sql: true
        temp:
          use_jdbc_metadata_defaults: false
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydb?currentSchema=coordination_schema
    username: myuser
    password: 123

  liquibase:
    change-log: classpath:changelog/db.changelog-master.xml